<?php
/**
 * Silver Touch Technologies Limited.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.silvertouch.com/MagentoExtensions/LICENSE.txt
 *
 * @category   Sttl
 * @package    Sttl_ImportOrders
 * @copyright  Copyright (c) 2011 Silver Touch Technologies Limited. (http://www.silvertouch.com/MagentoExtensions)
 * @license    http://www.silvertouch.com/MagentoExtensions/LICENSE.txt
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('SILVER Import Orders - Step2')?></h3></td>
			
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Run</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
<?php
$fields = Mage::helper('importOrders')->getCsvFields();
$input_fields = Mage::helper('importOrders')->getDefaultFields();

?>
<div id="__fieldmapping" style="">
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Field Mapping</h4>
    </div>
    <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post')?>" enctype="multipart/form-data">
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
			<?php foreach ($input_fields  as $input) : ?>
                <tr>
                    <td><?php echo "In Magento: " ?><b><span style="text-align:right"><?php echo $input ?></span></b></td>
                    <td>
						<--> In File:
						<b><select name="<?php echo $input ?>" style="width:250px;" ></b>
						<option value="<?php echo $input ?>"><?php echo "Select CSV attribute";?></option>
						<?php foreach ($fields  as $keyvalue => $value) : ?>
							<option value="<?php echo $value; ?>"><?php echo $value;?></option>
						<?php endforeach; ?>
						</select>
					</td>
                </tr>
			<?php endforeach; ?>
            </table>
        </fieldset>
    </form>
</div>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>