<?php
    $_order = $this->getOrder();
    $_shipments = $_order->getShipmentsCollection();
    $tracking_items = false;
    if ($_shipments) {
        $tracking_items = array();
        foreach ($_shipments as $_shipment) {
            foreach ($_shipment->getAllTracks() as $item) {
                $tracking_items[] = $item->getNumberDetail();
            }
        }
    }
    $_shippingAddress = $_order->getShippingAddress();
    $_billingAddress = $_order->getBillingAddress();
    $_items = $_order->getItemsCollection();
    $_paymentMethod = $_order->getPayment()->getMethod();
    $paymentMethod = Mage::app()->getConfig()->getNode('default/payment/' . $_paymentMethod)->title;
    $cod_fee = $_order->getCodFee();
    $customer = Mage::getModel('customer/customer')->load($_order->getCustomerId());
    $comment = $this->getComment();
    $currency = Mage::getModel('directory/currency');
?>
<?php
if ($comment) {
    echo $comment;
}
if ($tracking_items && is_array($tracking_items) && count($tracking_items) > 0) {
    echo "\n\n配送番号は以下のとおりです。\n\n";
    foreach ($tracking_items as $tracking_item) {
        echo $tracking_item['title'] . ": " . $tracking_item['number'] . "\n";
    }
}
?>

******************************************************************
　配送情報とご請求金額
******************************************************************

ご注文番号：<?php echo $_order->getIncrementId(); ?>

お支払合計：<?php echo $currency->formatTxt($_order->getGrandTotal()); ?>

ご決済方法：<?php echo $paymentMethod; ?>

　お届け日：<?php
if ($_order->getDeliveryDate()) {
    echo date('Y/m/d', strtotime($_order->getDeliveryDate()));
} else {
    echo '指定なし';
}
?>

メッセージ：<?php echo $_order->getCustomerComment(); ?>

◎お届け先
　お名前　：<?php echo $_shippingAddress->getLastname() . " " . $_shippingAddress->getFirstname(); ?>　様
　郵便番号：〒<?php echo $_shippingAddress->getPostcode(); ?>

　ご住所　：<?php echo $_shippingAddress->getRegion(); ?><?php echo $_shippingAddress->getCity(); ?><?php echo is_array($_shippingAddress->getStreet()) ? implode('', $_shippingAddress->getStreet()) : $_shippingAddress->getStreet(); ?>

　電話番号：<?php echo $_shippingAddress->getTelephone(); ?>


******************************************************************
　ご注文商品明細
******************************************************************

<?php foreach ($_items as $item): ?>
<?php $children = $item->getChildrenItems(); ?>
<?php if(count($children) > 0): ?>
<?php foreach ($children as $child): ?>
<!--<?php if($child->getPriceInclTax() = 0){ $price = $item->getPriceInclTax(); }else{ $price = $child->getPriceInclTax(); } ?>-->
商品名: <?php echo $child->getName(); ?>

商品コード: <?php echo $child->getSku(); ?>

数量：<?php echo (int)$child->getQtyOrdered(); ?> 個
金額：<?php echo $currency->formatTxt($price); ?>
小計：<?php echo $currency->formatTxt($item->getRowTotalInclTax()); ?>

<?php endforeach;?>
<?php endif; ?>
<?php
/*
$childs = $item->getChildrenItems();
echo get_class($childs[0]) ."\n\n";

$methods = get_class_methods(get_class($item));
echo get_class($item) . "\n";
foreach($methods as $method){echo $method . "\n";}
*/
?>

<?php endforeach; ?>
-----------------------------------------------------------
小　計 <?php echo $currency->formatTxt($_order->getSubtotalInclTax()); ?>
<?php if ((int)$_order->getDiscountAmount() != 0): ?>

値引き <?php echo $currency->formatTxt($_order->getDiscountAmount()); ?>
<?php endif; ?>

送　料 <?php echo $currency->formatTxt($_order->getShippingInclTax()); ?>
<?php if ((int)$_order->getCodFee() != 0): ?>

代引手数料 <?php echo $currency->formatTxt($_order->getCodFee()); ?>
<?php endif; ?>

===============================================================
合　計 <?php echo $currency->formatTxt($_order->getGrandTotal()); ?>

===============================================================
